{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Звіт до роботи\n",
    "## Тема: Віртуальні середовища\n",
    "### Мета роботи: Віртуальні середовища\n",
    "---\n",
    "### Виконання роботи\n",
    "1. Основи роботи з сторонніми бібліотеками\n",
    "    1. Перевірив наявність встановленного інструменту PIP (`Python Install Package`) за допомогою команди\n",
    "        - команда\n",
    "            ```bash\n",
    "            pip -V\n",
    "            ``` \n",
    "        - результат виконання\n",
    "            ```text\n",
    "            pip 22.3 from C:\\Users\\Worker\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pip (python 3.11)\n",
    "            ```\n",
    "    1. За допомогою команди `pip --help` передивися список команд які можна виконати за допомогою pip. Перевірив список встановлених на компютері бібліотек\n",
    "        - команда\n",
    "            ```bash\n",
    "            pip list\n",
    "            ``` \n",
    "        - результат виконання\n",
    "            ```text\n",
    "            Package           Version\n",
    "            ----------------- -------\n",
    "            asttokens         2.1.0\n",
    "            backcall          0.2.0\n",
    "            colorama          0.4.6\n",
    "            debugpy           1.6.3\n",
    "            decorator         5.1.1\n",
    "            entrypoints       0.4\n",
    "            executing         1.2.0\n",
    "            ipykernel         6.17.0\n",
    "            ipython           8.6.0\n",
    "            jedi              0.18.1\n",
    "            jupyter_client    7.4.4\n",
    "            jupyter_core      4.11.2\n",
    "            matplotlib-inline 0.1.6\n",
    "            nest-asyncio      1.5.6\n",
    "            packaging         21.3\n",
    "            parso             0.8.3\n",
    "            pickleshare       0.7.5\n",
    "            pip               22.3\n",
    "            prompt-toolkit    3.0.32\n",
    "            psutil            5.9.3\n",
    "            pure-eval         0.2.2\n",
    "            Pygments          2.13.0\n",
    "            pyparsing         3.0.9\n",
    "            python-dateutil   2.8.2\n",
    "            pywin32           305\n",
    "            pyzmq             24.0.1\n",
    "            setuptools        65.5.0\n",
    "            six               1.16.0\n",
    "            stack-data        0.6.0\n",
    "            tornado           6.2\n",
    "            traitlets         5.5.0\n",
    "            wcwidth           0.2.5\n",
    "            ```\n",
    "    1. За допомогою команди `pip install` встановив бібліотеку `requests`\n",
    "    1. Відкривши інтерпретатор python  виконав наступні команди \n",
    "        -  команди\n",
    "            ```bash\n",
    "            >>> import requests\n",
    "            >>> r = requests.get('https://google.com')\n",
    "            >>> r.status_code\n",
    "            >>> exit()\n",
    "            ```\n",
    "        - результат викнання `r.status_code`\n",
    "            ```text\n",
    "            200\n",
    "            ```\n",
    "    1. Ознайомився з іншими методами бібліотеки `requests`. Спробував виконати деякі з них\n",
    "        -  команди\n",
    "            ```bash\n",
    "            >>> import requests\n",
    "            >>> r = requests.post('https://httpbin.org/post', data={'key': 'value'})\n",
    "            >>> r.status_code\n",
    "            >>> exit()\n",
    "            ```\n",
    "        - результат викнання `r.status_code`\n",
    "            ```text\n",
    "            200\n",
    "            ```\n",
    "    1. Виконав наступні команди для роботи з бібліотекою `requests`\n",
    "        -  команда\n",
    "            ```bash\n",
    "            pip show requests\n",
    "            ```\n",
    "        - результат виконання \n",
    "            ```text\n",
    "            Name: requests\n",
    "            Version: 2.28.1\n",
    "            Summary: Python HTTP for Humans.\n",
    "            Home-page: https://requests.readthedocs.io\n",
    "            Author: Kenneth Reitz\n",
    "            Author-email: me@kennethreitz.org\n",
    "            License: Apache 2.0\n",
    "            Location: C:\\Users\\Worker\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\n",
    "            Requires: certifi, charset-normalizer, idna, urllib3\n",
    "            Required-by:\n",
    "            ```\n",
    "        -  команда\n",
    "            ```bash\n",
    "            pip install requests==2.1\n",
    "            ```\n",
    "        - результат виконання \n",
    "            ```text\n",
    "            Collecting requests==2.1\n",
    "            Downloading requests-2.1.0-py2.py3-none-any.whl (445 kB)\n",
    "                ---------------------------------------- 445.3/445.3 kB 2.8 MB/s eta 0:00:00\n",
    "            Installing collected packages: requests\n",
    "            Attempting uninstall: requests\n",
    "                Found existing installation: requests 2.28.1\n",
    "                Uninstalling requests-2.28.1:\n",
    "                Successfully uninstalled requests-2.28.1\n",
    "            Successfully installed requests-2.1.0\n",
    "            ```\n",
    "        -  команда\n",
    "            ```bash\n",
    "            pip show requests\n",
    "            ```\n",
    "        - результат виконання \n",
    "            ```text\n",
    "            Name: requests\n",
    "            Version: 2.1.0\n",
    "            Summary: Python HTTP for Humans.\n",
    "            Home-page: http://python-requests.org\n",
    "            Author: Kenneth Reitz\n",
    "            Author-email: me@kennethreitz.com\n",
    "            License: Copyright 2013 Kenneth Reitz\n",
    "            Location: C:\\Users\\Worker\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\n",
    "            Requires:\n",
    "            Required-by:\n",
    "            ```\n",
    "        -  команда\n",
    "            ```bash\n",
    "            pip uninstall requests\n",
    "            ```\n",
    "        - результат виконання \n",
    "            ```text\n",
    "            Found existing installation: requests 2.1.0\n",
    "            Uninstalling requests-2.1.0:\n",
    "            Would remove:\n",
    "                c:\\users\\worker\\appdata\\local\\programs\\python\\python311\\lib\\site-packages\\requests-2.1.0.dist-info\\*\n",
    "                c:\\users\\worker\\appdata\\local\\programs\\python\\python311\\lib\\site-packages\\requests\\*\n",
    "            Proceed (Y/n)?\n",
    "            Successfully uninstalled requests-2.1.0\n",
    "            ```\n",
    "1. Робота у віртуальному середовищі\n",
    "    1. Створив віртуальне середовище `VENV`\n",
    "        - команди\n",
    "            ```bash\n",
    "            python -m venv ./my_env\n",
    "            source my_env/Scripts/activate\n",
    "            pip install requests\n",
    "            deactivate\n",
    "            pip show requests\n",
    "            ```    \n",
    "        - результат виконання `pip show requests`\n",
    "            ```text \n",
    "            WARNING: Skipping reqeusts as it is not installed.\n",
    "            ```\n",
    "    1. Команда `pip show requests` вивела помилку, тому що не знайшла встановлену бібліотеку, через то що ми інсталювали її в середені віртуального середовища, і її не видно у загальній системі;\n",
    "\n",
    "1. Робота з Pipenv\n",
    "    1. За допомогою команди `pip install pipenv` встановив інструмент `pipenv`;\n",
    "    1. Список команд що можна виконати за допомогою `pipenv`:\n",
    "            ```bash\n",
    "            Commands:\n",
    "                check         Checks for PyUp Safety security vulnerabilities and against\n",
    "                                PEP 508 markers provided in Pipfile.\n",
    "                clean         Uninstalls all packages not specified in Pipfile.lock.\n",
    "                graph         Displays currently-installed dependency graph information.\n",
    "                install       Installs provided packages and adds them to Pipfile, or (if no\n",
    "                                packages are given), installs all packages from Pipfile.\n",
    "                lock          Generates Pipfile.lock.\n",
    "                open          View a given module in your editor.\n",
    "                requirements  Generate a requirements.txt from Pipfile.lock.\n",
    "                run           Spawns a command installed into the virtualenv.\n",
    "                scripts       Lists scripts in current environment config.\n",
    "                shell         Spawns a shell within the virtualenv.\n",
    "                sync          Installs all packages specified in Pipfile.lock.\n",
    "                uninstall     Uninstalls a provided package and removes it from Pipfile.\n",
    "                update        Runs lock, then sync.\n",
    "                verify        Verify the hash in Pipfile.lock is up-to-date.\n",
    "            ```\n",
    "    1. Виконав наступні команди для створення нового середовища та інсталяції бібліотеки: \n",
    "            ```bash\n",
    "            pipenv --python 3.10\n",
    "            pipenv --venv\n",
    "            pipenv run python -V\n",
    "            pipenv install requests\n",
    "            ```\n",
    "    1. У результаті виконання створилося два файли `Pipfile` та `Pipfile.lock`. У першому список бібліотек та залежностей, у другому json обєкт з хеш сумами;\n",
    "    1. Створив пайтон файл з наступним змістом:\n",
    "            ```python\n",
    "            import requests\n",
    "\n",
    "            response = requests.get('https://httpbin.org/')\n",
    "            for line in response.iter_lines():\n",
    "                print(line)\n",
    "            ```\n",
    "        - При виконанні програми з Visual Studio чи з командної стрічки видає помилку:\n",
    "            ```bash\n",
    "            Traceback (most recent call last):\n",
    "            File \"C:\\python_labs\\lab 6\\lab6.py\", line 1, in <module>\n",
    "                import requests\n",
    "            ModuleNotFoundError: No module named 'requests'\n",
    "            ```\n",
    "        - Після входу у віртуальне середовища за допомогою команди `pipenv shell` та виконання прогрми там, отримав html код вказаної веб-сторінки;\n",
    "            ```bash\n",
    "            ...\n",
    "            b'<head>'\n",
    "            b'    <meta charset=\"UTF-8\">'\n",
    "            b'    <title>httpbin.org</title>'\n",
    "            b'    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700\"'\n",
    "            b'        rel=\"stylesheet\">'\n",
    "            b'    <link rel=\"stylesheet\" type=\"text/css\" href=\"/flasgger_static/swagger-ui.css\">'\n",
    "            b'    <link rel=\"icon\" type=\"image/png\" href=\"/static/favicon.ico\" sizes=\"64x64 32x32 16x16\" />'\n",
    "            b'    <style>'\n",
    "            b'        html {'\n",
    "            b'            box-sizing: border-box;'\n",
    "            b'            overflow: -moz-scrollbars-vertical;'\n",
    "            b'            overflow-y: scroll;'\n",
    "            b'        }'\n",
    "            b''\n",
    "            b'        *,'\n",
    "            b'        *:before,'\n",
    "            b'        *:after {'\n",
    "            b'            box-sizing: inherit;'\n",
    "            b'        }'\n",
    "            b''\n",
    "            b'        body {'\n",
    "            b'            margin: 0;'\n",
    "            b'            background: #fafafa;'\n",
    "            b'        }'\n",
    "            b'    </style>'\n",
    "            b'</head>'\n",
    "            ...\n",
    "            \n",
    "            ```\n",
    "    1. Передивився різні бібліотеки на [Pypi](https://pypi.org/) та інсталював [camelcase](https://pypi.org/project/camelcase/). Написам програму для демонстрації роботи бібліотеки\n",
    "        - код програми\n",
    "            ```python\n",
    "            import camelcase\n",
    "            from camelcase import CamelCase\n",
    "\n",
    "            c = CamelCase()\n",
    "            s  = 'this is a sentence that needs CamelCasing!'\n",
    "            print(c.hump(s))\n",
    "            ```\n",
    "        - результат виконання\n",
    "            ```text\n",
    "            This is a Sentence That Needs CamelCasing!\n",
    "            ```\n",
    "    1. Переглянув список доступних інтерпретаторів за допомогою команди `Python: Select interpreter`\n",
    "        ![Image alt](img1.png)\n",
    "1. Робота зі змінними середовища\n",
    "    1. Створив файл `.env` та виконав наступний код:\n",
    "            ```python\n",
    "            import os\n",
    "            os.environ['HELLO']\n",
    "            ```\n",
    "    1. При виконанні коду без активації віртуального середовища отривам помилку:\n",
    "            ```text\n",
    "            Exception has occurred: KeyError\n",
    "                'HELLO'\n",
    "\n",
    "                During handling of the above exception, another exception occurred:\n",
    "\n",
    "                File \"C:\\python_labs\\lab 6\\lab6-3.py\", line 2, in <module>\n",
    "                    os.environ['HELLO']\n",
    "            ```\n",
    "\n",
    "### Висновок: \n",
    "-  В ході роботи я ознаймився з основами роботи із сторонніми бібліотеками, їх інсталяція та управління. Навчився встановлювати та налаштовлувати віртуальні середовища, працювати з ними;\n",
    "- Так, мету роботи досягнуто.\n",
    "- Всі, згідно вищезазначених завдань\n",
    "- У даній роботі питання відсутні)\n",
    "- Так, вдалось\n",
    "- Ні, не виникало.\n",
    "- Так, подобається.\n",
    "- Зменшити кількість питань у висновку)\n",
    "---"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.11.0 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "77d2cc0590bede01802f00adf8c77be78df7a889c0b833c69117dc8f16f8f23f"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
